{% set name = "qrcode" %}
{% set version = "8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qrcode-{{ version }}.tar.gz
  sha256: 025ce2b150f7fe4296d116ee9bad455a6643ab4f6e7dce541613a4758cbce347

build:
  entry_points:
    - qr = qrcode.console_scripts:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - colorama
  run_constrained:
    - pillow >=9.1.0

test:
  imports:
    - qrcode
    - qrcode.image
  commands:
    - pip check
    - qr --help
  requires:
    - pip

about:
  home: https://github.com/lincolnloop/python-qrcode
  summary: QR Code image generator
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
