{% set name = "qrcode" %}
{% set version = "8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qrcode-{{ version }}.tar.gz
  sha256: 025ce2b150f7fe4296d116ee9bad455a6643ab4f6e7dce541613a4758cbce347

build:
  number: 0
  noarch: python
  entry_points:
    - qr = qrcode.console_scripts:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - colorama
    - typing-extensions
    - pypng

test:
  imports:
    - qrcode
    - qrcode.image
  commands:
    - pip check
    - qr --help
  requires:
    - pip

about:
  home: https://github.com/lincolnloop/python-qrcode
  summary: QR Code image generator
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
